<a href="https://colab.research.google.com/github/hafsaaslam1212-star/northstar-analytics/blob/main/01_sql_in_r_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas numpy matplotlib seaborn pymongo

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Collecting pymongo
  Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 58.3 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 25.7 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.17.0

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
os.listdir('/content/drive/MyDrive/northstar_data')

['northstar_dataset']

In [ ]:
import os
os.listdir('/content/drive/MyDrive/northstar_data/northstar_dataset')

['complaints.csv',
 'README.txt',
 'deliveries.csv',
 'orders.csv',
 'app_events.csv',
 'customers.csv',
 'data_dictionary.csv',
 'vehicles.csv',
 'drivers.csv',
 'incidents.csv',
 'hubs.csv']

In [ ]:
for name, df in {
    "orders": orders,
    "deliveries": deliveries,
    "customers": customers,
    "drivers": drivers,
    "vehicles": vehicles,
    "hubs": hubs
}.items():
    print(f"\n{name}")
    print(df.head())
    print(df.info())

orders
  order_id customer_id service_type    order_created_at  \
0   O00001       C0292    Passenger 2024-08-20 14:43:00
1   O00002       C0459    Passenger 2024-05-14 22:16:00
2   O00003       C0161    Passenger 2025-09-02 14:37:00
3   O00004       C0520       Parcel 2025-01-11 17:15:00
4   O00005       C0558       Retail 2025-02-17 19:32:00

   promised_window_hours pickup_zone dropoff_zone priority_level  order_value  \
0                      6     Airport        South         Medium       126.65
1                     24       North      AIRPORT            Low       109.30
2                      4        West      AIRPORT           High        33.50
3                      2   RiverSide        North         Medium        10.04
4                     12   Riverside        SOUTH            Low       125.58

  booking_channel  special_handling_flag
0             App                      0
1             App                      0
2           Phone                      0
3             App                      1
4           Phone                      0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1250 non-null   object
 1   customer_id            1250 non-null   object
 2   service_type           1250 non-null   object
 3   order_created_at       1250 non-null   datetime64[ns]
 4   promised_window_hours  1250 non-null   int64
 5   pickup_zone            1250 non-null   object
 6   dropoff_zone           1250 non-null   object
 7   priority_level         1250 non-null   object
 8   order_value            1250 non-null   float64
 9   booking_channel        1225 non-null   object
 10  special_handling_flag  1250 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(7)
memory usage: 107.6+ KB
None

deliveries
  delivery_id order_id driver_id vehicle_id hub_id       dispatch_time  \
0     DL00001   O00938      D004       V056    H05 2024-06-18 10:57:00
1     DL00002   O00004      D138       V007    H02 2025-01-11 18:45:00
2     DL00003   O00639      D006       V049    H02 2025-06-02 20:39:00
3     DL00004   O00313      D116       V055    H02 2024-03-08 23:31:00
4     DL00005   O00844      D108       V034    H01 2025-09-21 11:43:00

       delivery_completed_at delivery_status  route_distance_km  \
0 2024-06-19 09:05:59.904311          Failed              17.26
1 2025-01-11 17:39:00.000000          OnTime              10.34
2 2025-06-02 21:45:32.366770          OnTime               7.92
3 2024-03-09 23:30:08.103702         Delayed              16.42
4 2025-09-21 15:45:34.131056          OnTime              14.52

   manual_route_override_count  proof_of_completion_missing  \
0                            1                            0
1                            1                            0
2                            0                            0
3                            0                            0
4                            1                            0

   customer_rating_post_delivery  fuel_or_charge_cost  delivery_duration_hrs  \
0                           3.07                12.05              22.149973
1                           5.00                13.41              -1.100000
2                           4.98                 8.51               1.108991
3                           4.18                13.62              23.985584
4                           4.18                 9.22               4.042814

   cost_per_km  is_failed
0     0.698146       True
1     1.296905      False
2     1.074495      False
3     0.829476      False
4     0.634986      False
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   delivery_id                    950 non-null    object
 1   order_id                       950 non-null    object
 2   driver_id                      950 non-null    object
 3   vehicle_id                     950 non-null    object
 4   hub_id                         950 non-null    object
 5   dispatch_time                  950 non-null    datetime64[ns]
 6   delivery_completed_at          931 non-null    datetime64[ns]
 7   delivery_status                950 non-null    object
 8   route_distance_km              950 non-null    float64
 9   manual_route_override_count    950 non-null    int64
 10  proof_of_completion_missing    950 non-null    int64
 11  customer_rating_post_delivery  936 non-null    float64
 12  fuel_or_charge_cost            950 non-null    float64
 13  delivery_duration_hrs          931 non-null    float64
 14  cost_per_km                    950 non-null    float64
 15  is_failed                      950 non-null    bool
dtypes: bool(1), datetime64[ns](2), float64(5), int64(2), object(6)
memory usage: 112.4+ KB
None

customers
  customer_id  age  home_zone customer_type          signup_date  \
0       C0001   26      North           SME  2024-11-27 04:25:00
1       C0002   61    AIRPORT      Consumer  2025-10-28 01:04:00
2       C0003   66       East      Consumer  2025-07-02 03:23:00
3       C0004   75    CENTRAL      Consumer  2025-08-19 01:58:00
4       C0005   26  Riverside      Consumer  2025-06-03 06:02:00

   loyalty_score  app_engagement_score preferred_channel account_status
0           44.9                  69.2               App         Active
1           55.4                  66.6               App         Active
2           75.9                  33.8               NaN         Active
3           32.5                  33.0               App         Active
4           55.9                 100.0               Web         Active
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           650 non-null    object
 1   age                   650 non-null    int64
 2   home_zone             650 non-null    object
 3   customer_type         650 non-null    object
 4   signup_date           650 non-null    object
 5   loyalty_score         630 non-null    float64
 6   app_engagement_score  650 non-null    float64
 7   preferred_channel     637 non-null    object
 8   account_status        650 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 45.8+ KB
None

drivers
  driver_id base_zone employment_type  years_experience  training_score  \
0      D001   AIRPORT        FullTime                 8            67.8
1      D002   Central        FullTime                 4            42.4
2      D003   AIRPORT        FullTime                11            96.5
3      D004   Airport        PartTime                13            88.9
4      D005     north        FullTime                 3            69.7

   driver_rating shift_preference  active_flag
0           3.54          Morning            1
1           3.94          Evening            1
2           5.00          Evening            1
3           4.75          Morning            1
4           4.14          Morning            1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   driver_id         170 non-null    object
 1   base_zone         170 non-null    object
 2   employment_type   170 non-null    object
 3   years_experience  170 non-null    int64
 4   training_score    163 non-null    float64
 5   driver_rating     170 non-null    float64
 6   shift_preference  170 non-null    object
 7   active_flag       170 non-null    int64
dtypes: float64(2), int64(2), object(4)
memory usage: 10.8+ KB
None

vehicles
  vehicle_id vehicle_type assigned_zone      commission_date  \
0       V001           EV         North  2024-12-28 23:48:00
1       V002           EV       AIRPORT  2024-04-21 16:14:00
2       V003     CargoVan         north  2025-11-24 23:59:00
3       V004       Hybrid     RiverSide  2024-06-07 13:21:00
4       V005     CargoVan          West  2025-11-15 11:08:00

   battery_health_pct  odometer_km maintenance_status telematics_version
0                71.8        56928             Active               v2.2
1                67.9       159368           InRepair               v2.2
2                91.7       219359             Active               v2.1
3                 NaN        36310             Active               v2.2
4                58.6       146638             Active               v2.2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   vehicle_id          120 non-null    object
 1   vehicle_type        120 non-null    object
 2   assigned_zone       120 non-null    object
 3   commission_date     120 non-null    object
 4   battery_health_pct  116 non-null    float64
 5   odometer_km         120 non-null    int64
 6   maintenance_status  120 non-null    object
 7   telematics_version  120 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 7.6+ KB
None

hubs
  hub_id        hub_name     zone   hub_type  capacity_score
0    H01  North Exchange    North   Dispatch              82
1    H02      South Link    South   Dispatch              78
2    H03       East Dock     East  Warehouse              74
3    H04       West Gate     West   Dispatch              69
4    H05    Central Core  Central    Control              88
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hub_id          8 non-null      object
 1   hub_name        8 non-null      object
 2   zone            8 non-null      object
 3   hub_type        8 non-null      object
 4   capacity_score  8 non-null      int64
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes
None

In [ ]:
#Data understanding
str(orders)
str(deliveries)
str(customers)

'data.frame':	1250 obs. of  11 variables:
 $ order_id             : chr  "O00001" "O00002" "O00003" "O00004" ...
 $ customer_id          : chr  "C0292" "C0459" "C0161" "C0520" ...
 $ service_type         : chr  "Passenger" "Passenger" "Passenger" "Parcel" ...
 $ order_created_at     : chr  "2024-08-20 14:43:00" "2024-05-14 22:16:00" "2025-09-02 14:37:00" "2025-01-11 17:15:00" ...
 $ promised_window_hours: int  6 24 4 2 12 1 2 4 12 6 ...
 $ pickup_zone          : chr  "Airport" "North" "West" "RiverSide" ...
 $ dropoff_zone         : chr  "South" "AIRPORT" "AIRPORT" "North" ...
 $ priority_level       : chr  "Medium" "Low" "High" "Medium" ...
 $ order_value          : num  126.7 109.3 33.5 10 125.6 ...
 $ booking_channel      : chr  "App" "App" "Phone" "App" ...
 $ special_handling_flag: int  0 0 0 1 0 1 0 0 0 0 ...
'data.frame':	950 obs. of  13 variables:
 $ delivery_id                  : chr  "DL00001" "DL00002" "DL00003" "DL00004" ...
 $ order_id                     : chr  "O00938" "O00004" "O00639" "O00313" ...
 $ driver_id                    : chr  "D004" "D138" "D006" "D116" ...
 $ vehicle_id                   : chr  "V056" "V007" "V049" "V055" ...
 $ hub_id                       : chr  "H05" "H02" "H02" "H02" ...
 $ dispatch_time                : chr  "2024-06-18 10:57:00" "2025-01-11 18:45:00" "2025-06-02 20:39:00" "2024-03-08 23:31:00" ...
 $ delivery_completed_at        : chr  "2024-06-19 09:05:59.904311" "2025-01-11 17:39:00.000000" "2025-06-02 21:45:32.366770" "2024-03-09 23:30:08.103702" ...
 $ delivery_status              : chr  "Failed" "OnTime" "OnTime" "Delayed" ...
 $ route_distance_km            : num  17.26 10.34 7.92 16.42 14.52 ...
 $ manual_route_override_count  : int  1 1 0 0 1 0 0 1 1 1 ...
 $ proof_of_completion_missing  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ customer_rating_post_delivery: num  3.07 5 4.98 4.18 4.18 1.57 4.64 3.76 3.7 3.2 ...
 $ fuel_or_charge_cost          : num  12.05 13.41 8.51 13.62 9.22 ...
'data.frame':	650 obs. of  9 variables:
 $ customer_id         : chr  "C0001" "C0002" "C0003" "C0004" ...
 $ age                 : int  26 61 66 75 26 41 54 70 34 23 ...
 $ home_zone           : chr  "North" "AIRPORT" "East" "CENTRAL" ...
 $ customer_type       : chr  "SME" "Consumer" "Consumer" "Consumer" ...
 $ signup_date         : chr  "2024-11-27 04:25:00" "2025-10-28 01:04:00" "2025-07-02 03:23:00" "2025-08-19 01:58:00" ...
 $ loyalty_score       : num  44.9 55.4 75.9 32.5 55.9 39.9 36.1 84.6 62.6 87.2 ...
 $ app_engagement_score: num  69.2 66.6 33.8 33 100 43.3 39 65.2 40.8 48.6 ...
 $ preferred_channel   : chr  "App" "App" "" "App" ...
 $ account_status      : chr  "Active" "Active" "Active" "Active" ...

In [ ]:
#HANDLE MISSING VALUES
colSums(is.na(orders))
colSums(is.na(deliveries))
colSums(is.na(customers))

             order_id           customer_id          service_type
                    0                     0                     0
     order_created_at promised_window_hours           pickup_zone
                    0                     0                     0
         dropoff_zone        priority_level           order_value
                    0                     0                     0
      booking_channel special_handling_flag
                    0                     0

                  delivery_id                      order_id
                            0                             0
                    driver_id                    vehicle_id
                            0                             0
                       hub_id                 dispatch_time
                            0                             0
        delivery_completed_at               delivery_status
                            0                             0
            route_distance_km   manual_route_override_count
                            0                             0
  proof_of_completion_missing customer_rating_post_delivery
                            0                            14
          fuel_or_charge_cost
                            0

         customer_id                  age            home_zone
                   0                    0                    0
       customer_type          signup_date        loyalty_score
                   0                    0                   20
app_engagement_score    preferred_channel       account_status
                   0                    0                    0

In [ ]:
install.packages("stringr")
library(stringr)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
#Remove Duplicates
orders <- distinct(orders)
deliveries <- distinct(deliveries)
customers <- distinct(customers)

In [ ]:
#Quality check
cat("Orders rows:", nrow(orders), "\n")
cat("Deliveries rows:", nrow(deliveries), "\n")
cat("Customers rows:", nrow(customers), "\n")

Orders rows: 1250
Deliveries rows: 950
Customers rows: 650

In [ ]:
clean_deliveries <- deliveries %>%
  filter(!is.na(delivery_status),
         !is.na(route_distance_km),
         route_distance_km > 0)

In [ ]:
#STANDARDISE TEXT FIELDS
orders$pickup_zone      <- str_to_title(trimws(orders$pickup_zone))
orders$dropoff_zone     <- str_to_title(trimws(orders$dropoff_zone))

customers$home_zone     <- str_to_title(trimws(customers$home_zone))
drivers$base_zone       <- str_to_title(trimws(drivers$base_zone))
vehicles$assigned_zone  <- str_to_title(trimws(vehicles$assigned_zone))
hubs$zone               <- str_to_title(trimws(hubs$zone))

deliveries$delivery_status <- str_to_title(trimws(deliveries$delivery_status))
complaints$severity <- str_to_title(trimws(complaints$severity))

### **SQL IN R ANALYTICS**

In [ ]:
install.packages("sqldf")
install.packages("dplyr")
install.packages("ggplot2")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘RSQLite’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
library(sqldf)
library(dplyr)
library(ggplot2)

Loading required package: gsubfn

Loading required package: proto

Warning message:
“no DISPLAY variable so Tk is not available”
Loading required package: RSQLite


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [ ]:
BASE = '/content/drive/MyDrive/northstar_data/northstar_dataset/'

In [ ]:
system("pip install -q pandas")

In [ ]:
orders <- read.csv("/content/drive/MyDrive/northstar_data/northstar_dataset/orders.csv")
deliveries <- read.csv("/content/drive/MyDrive/northstar_data/northstar_dataset/deliveries.csv")
customers <- read.csv("/content/drive/MyDrive/northstar_data/northstar_dataset/customers.csv")
drivers <- read.csv("/content/drive/MyDrive/northstar_data/northstar_dataset/drivers.csv")
vehicles <- read.csv("/content/drive/MyDrive/northstar_data/northstar_dataset/vehicles.csv")
hubs <- read.csv("/content/drive/MyDrive/northstar_data/northstar_dataset/hubs.csv")
incidents <- read.csv("/content/drive/MyDrive/northstar_data/northstar_dataset/incidents.csv")
complaints <- read.csv("/content/drive/MyDrive/northstar_data/northstar_dataset/complaints.csv")
app_events <- read.csv("/content/drive/MyDrive/northstar_data/northstar_dataset/app_events.csv")

In [ ]:
list.files("/content/drive/MyDrive/northstar_data/northstar_dataset/")

 [1] "app_events.csv"      "complaints.csv"      "customers.csv"
 [4] "data_dictionary.csv" "deliveries.csv"      "drivers.csv"
 [7] "hubs.csv"            "incidents.csv"       "orders.csv"
[10] "README.txt"          "vehicles.csv"

In [ ]:
sqldf("SELECT * FROM orders LIMIT 5")

  order_id customer_id service_type order_created_at    promised_window_hours
1 O00001   C0292       Passenger    2024-08-20 14:43:00  6
2 O00002   C0459       Passenger    2024-05-14 22:16:00 24
3 O00003   C0161       Passenger    2025-09-02 14:37:00  4
4 O00004   C0520       Parcel       2025-01-11 17:15:00  2
5 O00005   C0558       Retail       2025-02-17 19:32:00 12
  pickup_zone dropoff_zone priority_level order_value booking_channel
1 Airport     South        Medium         126.65      App
2 North       AIRPORT      Low            109.30      App
3 West        AIRPORT      High            33.50      Phone
4 RiverSide   North        Medium          10.04      App
5 Riverside   SOUTH        Low            125.58      Phone
  special_handling_flag
1 0
2 0
3 0
4 1
5 0

In [ ]:
#Delivery Status Distribution Analysis
sqldf("
SELECT delivery_status,
       COUNT(*) AS total_deliveries
FROM deliveries
GROUP BY delivery_status
ORDER BY total_deliveries DESC
")

  delivery_status total_deliveries
1 Ontime          616
2 Delayed         202
3 Failed          132

In [ ]:
#Hub Performance Analysis
sqldf("
SELECT h.hub_name,
       h.zone,
       d.delivery_status,
       COUNT(*) AS count
FROM deliveries d
JOIN hubs h ON d.hub_id = h.hub_id
GROUP BY h.hub_name, h.zone, d.delivery_status
ORDER BY h.hub_name
")

   hub_name       zone      delivery_status count
1  Airport Hub    Airport   Delayed         27
2  Airport Hub    Airport   Failed          15
3  Airport Hub    Airport   Ontime          62
4  Central Core   Central   Delayed         25
5  Central Core   Central   Failed          23
6  Central Core   Central   Ontime          67
7  East Dock      East      Delayed         23
8  East Dock      East      Failed          11
9  East Dock      East      Ontime          85
10 Midtown Relay  Central   Delayed         22
11 Midtown Relay  Central   Failed          26
12 Midtown Relay  Central   Ontime          80
13 North Exchange North     Delayed         26
14 North Exchange North     Failed          17
15 North Exchange North     Ontime          93
16 Riverside Hub  Riverside Delayed         25
17 Riverside Hub  Riverside Failed          14
18 Riverside Hub  Riverside Ontime          76
19 South Link     South     Delayed         26
20 South Link     South     Failed          10
21 South Link     South     Ontime          70
22 West Gate      West      Delayed         28
23 West Gate      West      Failed          16
24 West Gate      West      Ontime          83

In [ ]:
#Driver Behaviour Analysis
sqldf("
SELECT driver_id,
       COUNT(*) AS total_deliveries,
       AVG(manual_route_override_count) AS avg_overrides
FROM deliveries
GROUP BY driver_id
ORDER BY avg_overrides DESC
LIMIT 10
")

   driver_id total_deliveries avg_overrides
1  D112      2                4.500000
2  D127      6                2.833333
3  D021      2                2.500000
4  D139      5                2.000000
5  D130      8                2.000000
6  D124      4                2.000000
7  D105      7                2.000000
8  D085      4                2.000000
9  D079      2                2.000000
10 D069      7                2.000000

In [ ]:
#Customer Service Failure Analysis
sqldf("
SELECT c.customer_id,
       COUNT(DISTINCT cp.complaint_id) AS complaint_count,
       COUNT(DISTINCT d.delivery_id) AS deliveries
FROM customers c
LEFT JOIN complaints cp ON c.customer_id = cp.customer_id
LEFT JOIN orders o ON c.customer_id = o.customer_id
LEFT JOIN deliveries d ON o.order_id = d.order_id
GROUP BY c.customer_id
HAVING complaint_count >= 2
ORDER BY complaint_count DESC
")

   customer_id complaint_count deliveries
1  C0368       4               3
2  C0626       3               2
3  C0573       3               1
4  C0545       3               5
5  C0421       3               3
6  C0372       3               4
7  C0282       3               2
8  C0242       3               3
9  C0191       3               1
10 C0172       3               2
11 C0142       3               1
12 C0110       3               2
13 C0647       2               2
14 C0631       2               2
15 C0627       2               1
16 C0622       2               5
17 C0618       2               4
18 C0611       2               3
19 C0599       2               4
20 C0597       2               3
21 C0595       2               3
22 C0583       2               1
23 C0578       2               3
24 C0571       2               4
25 C0564       2               2
26 C0561       2               2
27 C0552       2               3
28 C0549       2               2
29 C0529       2               4
30 C0517       2               3
⋮  ⋮           ⋮               ⋮
45 C0325       2               1
46 C0285       2               1
47 C0279       2               1
48 C0272       2               0
49 C0269       2               0
50 C0259       2               3
51 C0248       2               1
52 C0208       2               2
53 C0180       2               2
54 C0178       2               2
55 C0162       2               1
56 C0157       2               4
57 C0146       2               2
58 C0140       2               2
59 C0138       2               1
60 C0119       2               2
61 C0100       2               1
62 C0095       2               1
63 C0078       2               3
64 C0056       2               2
65 C0054       2               3
66 C0051       2               2
67 C0032       2               2
68 C0028       2               1
69 C0026       2               2
70 C0023       2               5
71 C0015       2               2
72 C0012       2               3
73 C0004       2               2
74 C0001       2               2

In [ ]:
#Vehicle Performance and Incident Analysis
sqldf("
SELECT
  CASE
    WHEN v.battery_health_pct >= 80 THEN 'Good'
    WHEN v.battery_health_pct >= 60 THEN 'Fair'
    ELSE 'Poor'
  END AS battery_status,
  COUNT(i.incident_id) AS incidents
FROM vehicles v
JOIN deliveries d ON v.vehicle_id = d.vehicle_id
LEFT JOIN incidents i ON d.delivery_id = i.delivery_id
GROUP BY battery_status
")

  battery_status incidents
1 Fair           121
2 Good           115
3 Poor            44